query GET_REPORT(
        $initialDate:String!,
        $finalDate:String!,
        $status:String!,
        $cc:String,
        $orderformid:String, 
        $sellerId:String!,
        $page:Int!,
        $offset:Int!
        ) {
  devoluciones(
      initialDate: $initialDate,
      finalDate:$finalDate,
      status:$status,
      cc:$cc,
      orderformid:$orderformid, 
      sellerId:$sellerId,
      page:$page,
      offset:$offset
  ) @context(provider: "itglobers.reportlogic") {

    devoluciones {
     orderformid,
      fechacreado,
      seller{name,id},
      cliente{name, cedula, address, city},
      status, 
      totalprods,
      motivo,
      totaldevolucion,
      documentid
    },
    paginacion{page,pageSize, total}
    
    }
  
}


